// Icon catalog of the docs browser, taken from docs-react (same groups and order). Names are export names of
// @banzamel/mineralui-angular/icons (V2); icons-catalog.spec.ts checks that each one exists.
import type {IconTab} from '@kit/icon-browser/icon-browser'

export const PLAYGROUND_ICONS = [
    'mHomeIconV2',
    'mSearchIconV2',
    'mCalendarIconV2',
    'mSettingsIconV2',
    'mUserIconV2',
    'mChartIconV2',
    'mGitHubIconV2',
    'mMailIconV2',
    'mBellIconV2',
    'mHeartIconV2',
] as const

export const ICON_TABS: readonly IconTab[] = [
    {
        id: 'app',
        label: 'App icons',
        groups: [
            {
                title: 'Navigation',
                tone: 'Menus, movement and main app sections',
                items: [
                    'mHomeIconV2',
                    'mLayoutIconV2',
                    'mDashboardIconV2',
                    'mSidebarIconV2',
                    'mMenuIconV2',
                    'mChevronLeftIconV2',
                    'mChevronRightIconV2',
                    'mChevronDownIconV2',
                    'mChevronUpIconV2',
                    'mArrowLeftIconV2',
                    'mArrowRightIconV2',
                    'mArrowUpDownIconV2',
                    'mArrowUpIconV2',
                    'mArrowDownIconV2',
                ],
            },
            {
                title: 'Actions',
                tone: 'Common actions used in toolbars, buttons and lists',
                items: [
                    'mSearchIconV2',
                    'mHeartIconV2',
                    'mHeartFillIconV2',
                    'mEditIconV2',
                    'mPlusIconV2',
                    'mMinusIconV2',
                    'mDownloadIconV2',
                    'mUploadIconV2',
                    'mCloseIconV2',
                    'mCheckIconV2',
                    'mCheckCircleIconV2',
                    'mCopyIconV2',
                    'mRefreshIconV2',
                    'mEllipsisVerticalIconV2',
                    'mEllipsisHorizontalIconV2',
                    'mFilterIconV2',
                    'mSortIconV2',
                    'mShareIconV2',
                    'mSendIconV2',
                    'mLinkIconV2',
                    'mPlayIconV2',
                    'mStopIconV2',
                    'mBookmarkIconV2',
                    'mBookmarkFillIconV2',
                    'mPrinterIconV2',
                    'mAttachIconV2',
                    'mExternalLinkIconV2',
                    'mBoltIconV2',
                    'mHistoryIconV2',
                    'mZoomInIconV2',
                    'mZoomOutIconV2',
                    'mClickIconV2',
                    'mMagicIconV2',
                    'mMoveIconV2',
                    'mResizeIconV2',
                    'mUndoIconV2',
                    'mRedoIconV2',
                ],
            },
            {
                title: 'People and contact',
                tone: 'Users, contact, language and app communication',
                items: [
                    'mUserIconV2',
                    'mUsersIconV2',
                    'mTeamIconV2',
                    'mGroupIconV2',
                    'mUserPlusIconV2',
                    'mUserMinusIconV2',
                    'mUserCheckIconV2',
                    'mMailIconV2',
                    'mMailOpenIconV2',
                    'mBellIconV2',
                    'mPhoneIconV2',
                    'mChatIconV2',
                    'mChatsIconV2',
                    'mCommentIconV2',
                    'mGlobeIconV2',
                    'mTranslateIconV2',
                    'mHelpIconV2',
                    'mPinIconV2',
                    'mBuildingIconV2',
                ],
            },
            {
                title: 'Views and media',
                tone: 'Working views, forms, media and theme mode',
                items: [
                    'mCalendarIconV2',
                    'mSettingsIconV2',
                    'mChartIconV2',
                    'mEyeIconV2',
                    'mEyeOffIconV2',
                    'mClockIconV2',
                    'mImageIconV2',
                    'mGalleryIconV2',
                    'mCameraIconV2',
                    'mMoonIconV2',
                    'mSunIconV2',
                    'mCreditCardIconV2',
                    'mBankIconV2',
                    'mIdCardIconV2',
                    'mListIconV2',
                    'mColumnsIconV2',
                    'mPaletteIconV2',
                    'mQrCodeIconV2',
                    'mTerminalIconV2',
                    'mSlidersIconV2',
                    'mDeviceMonitorIconV2',
                    'mDevicePhoneIconV2',
                    'mDeviceTabletIconV2',
                    'mKanbanIconV2',
                    'mFormIconV2',
                    'mWindowIconV2',
                    'mCubeIconV2',
                    'mPuzzleIconV2',
                    'mCopyrightIconV2',
                ],
            },
            {
                title: 'Files and system',
                tone: 'Documents, storage, protection and status feedback',
                items: [
                    'mStarIconV2',
                    'mStarFillIconV2',
                    'mTrashIconV2',
                    'mLockIconV2',
                    'mLockOpenIconV2',
                    'mFolderIconV2',
                    'mFolderOpenIconV2',
                    'mFolderPlusIconV2',
                    'mFileIconV2',
                    'mDocIconV2',
                    'mDocPlusIconV2',
                    'mDocCopyIconV2',
                    'mWarningIconV2',
                    'mInfoIconV2',
                    'mErrorIconV2',
                    'mSuccessIconV2',
                    'mNeutralIconV2',
                    'mTagIconV2',
                    'mClipboardIconV2',
                    'mCartIconV2',
                    'mLightbulbIconV2',
                    'mBugIconV2',
                    'mDatabaseIconV2',
                    'mArchiveIconV2',
                    'mKeyIconV2',
                    'mProtectIconV2',
                    'mBoxIconV2',
                    'mDollarIconV2',
                    'mEuroIconV2',
                    'mSignal1IconV2',
                    'mSignal2IconV2',
                    'mSignal3IconV2',
                    'mSignal4IconV2',
                    'mTaskIconV2',
                    'mUrgentIconV2',
                ],
            },
            {
                title: 'Education',
                tone: 'Learning materials, lessons and classroom contexts',
                items: [
                    'mLessonIconV2',
                    'mClassroomIconV2',
                    'mBookIconV2',
                    'mBooksIconV2',
                    'mBookOpenIconV2',
                    'mBookOpenFillIconV2',
                ],
            },
            {
                title: 'Places',
                tone: 'Rooms, apartments and storefront locations',
                items: [
                    'mRoomIconV2',
                    'mFlatIconV2',
                    'mHouseIconV2',
                    'mApartmentIconV2',
                    'mShopIconV2',
                    'mBasketIconV2',
                ],
            },
            {
                title: 'Transport',
                tone: 'Vehicles, shipping and travel scenarios',
                items: ['mCarIconV2', 'mCarFillIconV2', 'mShipIconV2', 'mAirplaneIconV2', 'mAirplaneFillIconV2'],
            },
        ],
    },
    {
        id: 'flags',
        label: 'Flags',
        groups: [
            {
                title: 'Flags',
                tone: 'Country flags for phone, language and locale selectors',
                items: [
                    'mFlagPlIconV2',
                    'mFlagUsIconV2',
                    'mFlagGbIconV2',
                    'mFlagDeIconV2',
                    'mFlagFrIconV2',
                    'mFlagUaIconV2',
                    'mFlagEsIconV2',
                    'mFlagItIconV2',
                    'mFlagCnIconV2',
                    'mFlagCzIconV2',
                    'mFlagSkIconV2',
                    'mFlagJpIconV2',
                    'mFlagRuIconV2',
                    'mFlagArIconV2',
                    'mFlagBrIconV2',
                    'mFlagInIconV2',
                    'mFlagCaIconV2',
                    'mFlagMxIconV2',
                    'mFlagNlIconV2',
                    'mFlagSeIconV2',
                    'mFlagNoIconV2',
                    'mFlagKrIconV2',
                    'mFlagTrIconV2',
                    'mFlagAuIconV2',
                    'mFlagChIconV2',
                    'mFlagIeIconV2',
                    'mFlagAtIconV2',
                    'mFlagPtIconV2',
                ],
            },
        ],
    },
    {
        id: 'brands',
        label: 'Brands',
        groups: [{title: 'Brands', tone: 'Brand scenes in the v2 style', items: ['mGitHubIconV2']}],
    },
]
