// Icon catalog of the docs browser, taken from docs-react (same groups and order). Names are export names of
// @banzamel/mineralui-angular/icons; icons-catalog.spec.ts checks that each one exists.
import type {IconTab} from '@kit/icon-browser/icon-browser'

export const PLAYGROUND_ICONS = [
    'mHomeIcon',
    'mSearchIcon',
    'mCalendarIcon',
    'mSettingsIcon',
    'mUserIcon',
    'mChartIcon',
] as const

export const NEW_ICONS: ReadonlySet<string> = new Set(['mWalletIcon', 'mCoinIcon', 'mMoneyIcon', 'mReceiptIcon'])

export const ICON_TABS: readonly IconTab[] = [
    {
        id: 'app',
        label: 'App icons',
        groups: [
            {
                title: 'Navigation',
                tone: 'Menus, movement and main app sections',
                items: [
                    'mHomeIcon',
                    'mLayoutIcon',
                    'mDashboardIcon',
                    'mSidebarIcon',
                    'mMenuIcon',
                    'mChevronLeftIcon',
                    'mChevronRightIcon',
                    'mChevronDownIcon',
                    'mChevronUpIcon',
                    'mArrowLeftIcon',
                    'mArrowRightIcon',
                    'mArrowUpDownIcon',
                    'mArrowUpIcon',
                    'mArrowDownIcon',
                ],
            },
            {
                title: 'Actions',
                tone: 'Common actions used in toolbars, buttons and lists',
                items: [
                    'mSearchIcon',
                    'mCloseIcon',
                    'mPlusIcon',
                    'mMinusIcon',
                    'mEllipsisVerticalIcon',
                    'mFilterIcon',
                    'mSortIcon',
                    'mEditIcon',
                    'mCopyIcon',
                    'mDownloadIcon',
                    'mExternalLinkIcon',
                    'mEllipsisHorizontalIcon',
                    'mZoomInIcon',
                    'mZoomOutIcon',
                    'mUploadIcon',
                    'mHeartIcon',
                    'mHeartFillIcon',
                    'mCheckIcon',
                    'mCheckCircleIcon',
                    'mClickIcon',
                    'mBoltIcon',
                    'mRefreshIcon',
                    'mSendIcon',
                    'mAttachIcon',
                    'mLinkIcon',
                    'mMagicIcon',
                    'mMoveIcon',
                    'mPlayIcon',
                    'mStopIcon',
                    'mResizeIcon',
                    'mShareIcon',
                    'mPrinterIcon',
                    'mHistoryIcon',
                    'mUndoIcon',
                    'mRedoIcon',
                    'mBookmarkIcon',
                    'mBookmarkFillIcon',
                ],
            },
            {
                title: 'People and contact',
                tone: 'Users, contact, language and app communication',
                items: [
                    'mUserIcon',
                    'mUsersIcon',
                    'mTeamIcon',
                    'mGroupIcon',
                    'mUserPlusIcon',
                    'mUserMinusIcon',
                    'mUserCheckIcon',
                    'mMailIcon',
                    'mMailOpenIcon',
                    'mPhoneIcon',
                    'mGlobeIcon',
                    'mPinIcon',
                    'mHelpIcon',
                    'mBuildingIcon',
                    'mBellIcon',
                    'mTranslateIcon',
                    'mChatIcon',
                    'mChatsIcon',
                    'mCommentIcon',
                ],
            },
            {
                title: 'Views and media',
                tone: 'Working views, forms, media and theme mode',
                items: [
                    'mGalleryIcon',
                    'mImageIcon',
                    'mCameraIcon',
                    'mDeviceMonitorIcon',
                    'mDevicePhoneIcon',
                    'mDeviceTabletIcon',
                    'mKanbanIcon',
                    'mFormIcon',
                    'mSlidersIcon',
                    'mTerminalIcon',
                    'mWindowIcon',
                    'mCubeIcon',
                    'mPaletteIcon',
                    'mPuzzleIcon',
                    'mCalendarIcon',
                    'mClockIcon',
                    'mCopyrightIcon',
                    'mChartIcon',
                    'mQrCodeIcon',
                    'mCreditCardIcon',
                    'mBankIcon',
                    'mWalletIcon',
                    'mCoinIcon',
                    'mMoneyIcon',
                    'mReceiptIcon',
                    'mIdCardIcon',
                    'mEyeIcon',
                    'mEyeOffIcon',
                    'mSunIcon',
                    'mMoonIcon',
                    'mSettingsIcon',
                    'mMakeupIcon',
                    'mListIcon',
                    'mColumnsIcon',
                ],
            },
            {
                title: 'Files and system',
                tone: 'Documents, storage, protection and status feedback',
                items: [
                    'mFileIcon',
                    'mDocIcon',
                    'mDocPlusIcon',
                    'mDocCopyIcon',
                    'mFolderIcon',
                    'mFolderOpenIcon',
                    'mFolderPlusIcon',
                    'mBoxIcon',
                    'mDatabaseIcon',
                    'mProtectIcon',
                    'mLockIcon',
                    'mLockOpenIcon',
                    'mClipboardIcon',
                    'mTagIcon',
                    'mCartIcon',
                    'mDollarIcon',
                    'mEuroIcon',
                    'mBugIcon',
                    'mLightbulbIcon',
                    'mSignal1Icon',
                    'mSignal2Icon',
                    'mSignal3Icon',
                    'mSignal4Icon',
                    'mWarningIcon',
                    'mInfoIcon',
                    'mErrorIcon',
                    'mSuccessIcon',
                    'mNeutralIcon',
                    'mStarIcon',
                    'mStarFillIcon',
                    'mTrashIcon',
                    'mArchiveIcon',
                    'mKeyIcon',
                    'mTaskIcon',
                    'mUrgentIcon',
                ],
            },
            {
                title: 'Education',
                tone: 'Learning materials, lessons and classroom contexts',
                items: [
                    'mLessonIcon',
                    'mClassroomIcon',
                    'mBookIcon',
                    'mBooksIcon',
                    'mBookOpenIcon',
                    'mBookOpenFillIcon',
                ],
            },
            {
                title: 'Places',
                tone: 'Rooms, apartments and storefront locations',
                items: ['mRoomIcon', 'mFlatIcon', 'mHouseIcon', 'mApartmentIcon', 'mShopIcon', 'mBasketIcon'],
            },
            {
                title: 'Transport',
                tone: 'Vehicles, shipping and travel scenarios',
                items: ['mCarIcon', 'mCarFillIcon', 'mShipIcon', 'mAirplaneIcon', 'mAirplaneFillIcon'],
            },
        ],
    },
    {
        id: 'files',
        label: 'File types',
        groups: [
            {
                title: 'General file types',
                tone: 'Common file families used across lists and previews',
                items: [
                    'mFileTextIcon',
                    'mFilePdfIcon',
                    'mFileImageIcon',
                    'mFileCodeIcon',
                    'mFileArchiveIcon',
                    'mFileVideoIcon',
                ],
            },
            {
                title: 'Specific extensions',
                tone: 'Explicit extension icons ready for tree view mapping',
                items: [
                    'mFileTxtIcon',
                    'mFileDocsIcon',
                    'mFileJpgIcon',
                    'mFileJsonIcon',
                    'mFileExeIcon',
                    'mFileOdtIcon',
                    'mFileMdIcon',
                    'mFileJsIcon',
                    'mFileHtmlIcon',
                    'mFileCssIcon',
                    'mFilePhpIcon',
                    'mFilePngIcon',
                    'mFileSvgIcon',
                    'mFileGifIcon',
                    'mFileWebpIcon',
                    'mFileTsIcon',
                    'mFileTsxIcon',
                    'mFileJsxIcon',
                    'mFileXmlIcon',
                    'mFileCsvIcon',
                    'mFileXlsIcon',
                    'mFilePptIcon',
                    'mFileZipIcon',
                    'mFileRarIcon',
                    'mFileMp3Icon',
                    'mFileMp4Icon',
                ],
            },
        ],
    },
    {
        id: 'flags',
        label: 'Flags',
        groups: [
            {
                title: 'Flags',
                tone: 'Country flags for phone, language and locale selectors',
                items: [
                    'mFlagPlIcon',
                    'mFlagUsIcon',
                    'mFlagGbIcon',
                    'mFlagDeIcon',
                    'mFlagRuIcon',
                    'mFlagArIcon',
                    'mFlagBrIcon',
                    'mFlagInIcon',
                    'mFlagCaIcon',
                    'mFlagMxIcon',
                    'mFlagEsIcon',
                    'mFlagFrIcon',
                    'mFlagItIcon',
                    'mFlagCnIcon',
                    'mFlagCzIcon',
                    'mFlagSkIcon',
                    'mFlagJpIcon',
                    'mFlagUaIcon',
                    'mFlagNlIcon',
                    'mFlagSeIcon',
                    'mFlagNoIcon',
                    'mFlagKrIcon',
                    'mFlagTrIcon',
                    'mFlagAuIcon',
                    'mFlagChIcon',
                    'mFlagIeIcon',
                    'mFlagAtIcon',
                    'mFlagPtIcon',
                ],
            },
        ],
    },
    {
        id: 'brands',
        label: 'Brands',
        groups: [
            {
                title: 'Mono brands',
                tone: 'Single-color brand marks for buttons, outlines and neutral layouts',
                items: [
                    'mGoogleIcon',
                    'mAppleIcon',
                    'mAmazonIcon',
                    'mAmericanExpressIcon',
                    'mFacebookIcon',
                    'mInstagramIcon',
                    'mLinkedInIcon',
                    'mYouTubeIcon',
                    'mGitHubIcon',
                    'mDiscordIcon',
                    'mFigmaIcon',
                    'mXIcon',
                    'mSlackIcon',
                    'mMastercardIcon',
                    'mDiscoverIcon',
                    'mMaestroIcon',
                    'mVisaIcon',
                    'mLetsEncryptIcon',
                    'mMicrosoftIcon',
                    'mPinterestIcon',
                    'mPayPalIcon',
                    'mSpotifyIcon',
                    'mTumblrIcon',
                    'mUnityIcon',
                    'mVimeoIcon',
                    'mVkIcon',
                ],
            },
            {
                title: 'Color brands',
                tone: 'Color brand marks for social blocks and branded entry points',
                items: [
                    'mGoogleColorIcon',
                    'mAppleColorIcon',
                    'mAmazonColorIcon',
                    'mAmericanExpressColorIcon',
                    'mFacebookColorIcon',
                    'mInstagramColorIcon',
                    'mLinkedInColorIcon',
                    'mYouTubeColorIcon',
                    'mGitHubColorIcon',
                    'mDiscordColorIcon',
                    'mFigmaColorIcon',
                    'mXColorIcon',
                    'mSlackColorIcon',
                    'mMastercardColorIcon',
                    'mDiscoverColorIcon',
                    'mMaestroColorIcon',
                    'mVisaColorIcon',
                    'mLetsEncryptColorIcon',
                    'mMicrosoftColorIcon',
                    'mPinterestColorIcon',
                    'mPayPalColorIcon',
                    'mSpotifyColorIcon',
                    'mTumblrColorIcon',
                    'mUnityColorIcon',
                    'mVimeoColorIcon',
                    'mVkColorIcon',
                ],
            },
        ],
    },
]
