// Scene order and labels from docs-react. Names are export names of @banzamel/mineralui-angular/illustrations.
export const SCENES: readonly {readonly name: string; readonly label: string}[] = [
    {name: 'mDashboardIllustration', label: 'Dashboard'},
    {name: 'mAnalyticsIllustration', label: 'Analytics'},
    {name: 'mCalendarIllustration', label: 'Calendar'},
    {name: 'mMailIllustration', label: 'Mail'},
    {name: 'mNotificationsIllustration', label: 'Notifications'},
    {name: 'mChatIllustration', label: 'Chat'},
    {name: 'mMasonryIllustration', label: 'Masonry'},
    {name: 'mDatePickerIllustration', label: 'Date Picker'},
    {name: 'mDateRangePickerIllustration', label: 'Date Range Picker'},
    {name: 'mShowcaseIllustration', label: 'Showcase'},
    {name: 'mCalendarBoardIllustration', label: 'Calendar Board'},
    {name: 'mFileManagerIllustration', label: 'File Manager'},
    {name: 'mQrCodeIllustration', label: 'QR Code'},
    {name: 'mCountUpIllustration', label: 'Count Up'},
    {name: 'mTimeAgoIllustration', label: 'Time Ago'},
    {name: 'mI18nIllustration', label: 'i18n'},
    {name: 'mIconsIllustration', label: 'Icons'},
    {name: 'mFormsIllustration', label: 'Forms'},
    {name: 'mTopbarIllustration', label: 'Topbar'},
    {name: 'mSidebarIllustration', label: 'Sidebar'},
    {name: 'mDataTableIllustration', label: 'Data Table'},
    {name: 'mTaskListIllustration', label: 'Task List'},
    {name: 'mNavbarIllustration', label: 'Navbar'},
    {name: 'mGalleryIllustration', label: 'Gallery'},
    {name: 'mSearchIllustration', label: 'Search'},
    {name: 'mSettingsIllustration', label: 'Settings'},
    {name: 'mSecurityIllustration', label: 'Security'},
    {name: 'mWalletIllustration', label: 'Wallet'},
    {name: 'mTeamIllustration', label: 'Team'},
    {name: 'mUploadIllustration', label: 'Upload'},
    {name: 'mOnboardingIllustration', label: 'Onboarding'},
    {name: 'mSuccessIllustration', label: 'Success'},
    {name: 'mErrorIllustration', label: 'Error'},
    {name: 'mNotFoundIllustration', label: 'Not Found'},
    {name: 'mEmptyStateIllustration', label: 'Empty State'},
    {name: 'mStudentIllustration', label: 'Student'},
    {name: 'mTeacherIllustration', label: 'Teacher'},
    {name: 'mTutorIllustration', label: 'Tutor'},
    {name: 'mFamilyIllustration', label: 'Family'},
    {name: 'mCorporateIllustration', label: 'Corporate'},
    {name: 'mOfficeIllustration', label: 'Office'},
    {name: 'mAccountantIllustration', label: 'Accountant'},
    {name: 'mListeningIllustration', label: 'Listening'},
    {name: 'mSpeakingIllustration', label: 'Speaking'},
    {name: 'mReadingIllustration', label: 'Reading'},
    {name: 'mWritingIllustration', label: 'Writing'},
    {name: 'mCourseIllustration', label: 'Course'},
    {name: 'mClassroomIllustration', label: 'Classroom'},
    {name: 'mOnlineLessonIllustration', label: 'Online Lesson'},
    {name: 'mGroupClassIllustration', label: 'Group Class'},
    {name: 'mEnrollmentIllustration', label: 'Enrollment'},
    {name: 'mAttendanceIllustration', label: 'Attendance'},
    {name: 'mExamIllustration', label: 'Exam'},
    {name: 'mCertificateIllustration', label: 'Certificate'},
    {name: 'mProgressIllustration', label: 'Progress'},
    {name: 'mReviewIllustration', label: 'Review'},
    {name: 'mLibraryIllustration', label: 'Library'},
    {name: 'mWorkbookIllustration', label: 'Workbook'},
    {name: 'mAudioFileIllustration', label: 'Audio File'},
    {name: 'mInvoiceIllustration', label: 'Invoice'},
    {name: 'mReceiptIllustration', label: 'Receipt'},
    {name: 'mRefundIllustration', label: 'Refund'},
    {name: 'mConflictIllustration', label: 'Conflict'},
]
